### ISSUE TITLE
hot wallet zombie issue

### ISSUE THREAD

**Issue by hongcoiner** [hongcoin/DO#113]
zombie fund issue.

**Comment by hongcoiner** [comment]
as it anyway can't be solved in this version.

**Comment by Hibryda** [comment]
Cannot be solved in any version, as it's not HONG's problem.
There is no remedy, as Polo wallet is crippled. Actually it's not a wallet in pure sense. User on Poloniex has access to some basic operations only, further they are performed via hot wallet (one for many users) of Poloniex. It's a known issue, as many ppl before sent money to some contracts. It's not our problem, Polo surely has disclaimers about the fact that their "wallet" isn't actual wallet. The only way users can deal with it is to ask Poloniex to run a function on their behalf and repay money to their virtual accounts there.
As all txs are registered on Poloniex's side user can safely deal with their support and prove transactions being made. So I assume there is way to redeem. On the other hand, Hong provides interface as promised, to all fully functional wallets. It's not Hong's issue to fix tools provided by third parties.
There is no other viable redesign scheme than just adding a big red banner stating: "_Only true Ethereum network wallets can interact fully with this contract! Make sure you understand the tool you use!_"
Also, the only entity that can be held responsible for user's problems (besides user him/herself) with accessing contract functions is Poloniex (or any other exchange having virtual wallets) as they enter this way in possession of funds not belonging to them (actual account that owns funds belongs to Poloniex). HONG contract just served as expected.

**Comment by phiferd** [comment]
One option that would help to limit this issue is to disable the fallback in the HONG contract.   i.e.

```
function () {
     throw;
}
```

if the only way to invest in the fund is to call "buyTokens", then it implies the user has some capability to make a function call, which means they should also be able to call other functions, such as "refund".  It may not be perfect, but I think it would prevent this particular issue.

**Comment by Hibryda** [comment]
@phiferd To some extent - yes. But this would complicate things for regular users.
